### ISSUE TITLE
readme function fails on install

### ISSUE THREAD

**Issue by nachopro** [storborg/python-packaging#12]
How can I solve this issue ? Thanks!

Collecting test
  Downloading http://pypi.example.com/repository/2/test-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-EAllOQ/test/setup.py", line 11, in <module>
        long_description=readme(),
      File "/tmp/pip-build-EAllOQ/test/setup.py", line 4, in readme
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by nachopro** [comment]
So sorry :(

http://stackoverflow.com/questions/29150804/file-openreadme-in-setup-py-isnt-found
